[package]
name = "jsp-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
lsp-types = "0.97.0"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
tower-lsp = "0.20.0"
